version: 2

sources:
  - name: raw_segment_android__production_events
    tables:
      - name: community_viewed_article
        columns:
        - name: anonymous_id
        - name: article_id
        - name: category
        - name: context_app_build
        - name: context_app_name
        - name: context_app_namespace
        - name: context_app_version
        - name: context_device_id
        - name: context_device_manufacturer
        - name: context_device_model
        - name: context_device_name
        - name: context_device_token
        - name: context_device_type
        - name: context_ip
        - name: context_library_name
        - name: context_library_version
        - name: context_locale
        - name: context_network_bluetooth
        - name: context_network_cellular
        - name: context_network_wifi
        - name: context_os_name
        - name: context_os_version
        - name: context_screen_density
        - name: context_screen_height
        - name: context_screen_width
        - name: context_timezone
        - name: context_user_agent
        - name: event
        - name: event_text
        - name: id
        - name: loaded_at
        - name: original_timestamp
        - name: received_at
        - name: referrer
        - name: sent_at
        - name: slug
        - name: timestamp
        - name: user_id
        - name: uuid_ts
      - name: screens
        columns:
        - name: anonymous_id
        - name: category
        - name: context_app_build
        - name: context_app_name
        - name: context_app_namespace
        - name: context_app_version
        - name: context_device_id
        - name: context_device_manufacturer
        - name: context_device_model
        - name: context_device_name
        - name: context_device_token
        - name: context_device_type
        - name: context_ip
        - name: context_library_name
        - name: context_library_version
        - name: context_locale
        - name: context_network_bluetooth
        - name: context_network_cellular
        - name: context_network_wifi
        - name: context_os_name
        - name: context_os_version
        - name: context_screen_density
        - name: context_screen_height
        - name: context_screen_width
        - name: context_timezone
        - name: context_user_agent
        - name: id
        - name: loaded_at
        - name: name
        - name: original_timestamp
        - name: part
        - name: previous_treatment
        - name: received_at
        - name: reload
        - name: sent_at
        - name: timestamp
        - name: user_id
        - name: uuid_ts
        - name: guide_title
        - name: article_id
        - name: referrer
        - name: slug
        - name: clinic_id
