version: 2

sources:
  - name: raw_segment_ios__production_events
    tables:
      - name: community_viewed_article
        columns:
        - name: context_app_version
        - name: context_device_id
        - name: context_device_manufacturer
        - name: context_device_model
        - name: context_device_name
        - name: context_device_token
        - name: context_device_type
        - name: context_ip
        - name: context_library_name
        - name: context_library_version
        - name: context_locale
        - name: context_network_carrier
        - name: context_network_cellular
        - name: context_network_wifi
        - name: context_os_name
        - name: context_os_version
        - name: context_screen_height
        - name: context_screen_width
        - name: context_timezone
        - name: context_traits_anonymous_id
        - name: context_traits_app_user
        - name: context_traits_email
        - name: context_traits_notification_permission_status
        - name: context_traits_treatment_country
        - name: context_traits_trial
        - name: context_traits_trial_end
        - name: context_traits_trial_start
        - name: context_traits_user_id
        - name: event
        - name: event_text
        - name: id
        - name: loaded_at
        - name: original_timestamp
        - name: reading_session
        - name: reading_time
        - name: received_at
        - name: referrer
        - name: sent_at
        - name: slug
        - name: timestamp
        - name: user_id
        - name: uuid_ts
        - name: context_traits_latest_purchase_date
        - name: context_traits_original_purchase_date
        - name: context_traits_plan
        - name: clinic_id
        - name: context_traits_promo
        - name: context_traits_promo_date
        - name: context_traits_received_promo
        - name: context_traits_internal
        - name: article_id
      - name: viewed_article
        columns:
        - name: anonymous_id
        - name: category
        - name: context_app_build
        - name: context_app_name
        - name: context_app_namespace
        - name: context_app_version
        - name: context_device_id
        - name: context_device_manufacturer
        - name: context_device_model
        - name: context_device_name
        - name: context_device_token
        - name: context_device_type
        - name: context_ip
        - name: context_library_name
        - name: context_library_version
        - name: context_locale
        - name: context_network_carrier
        - name: context_network_cellular
        - name: context_network_wifi
        - name: context_os_name
        - name: context_os_version
        - name: context_screen_height
        - name: context_screen_width
        - name: context_timezone
        - name: context_traits_anonymous_id
        - name: context_traits_app_user
        - name: context_traits_email
        - name: context_traits_latest_purchase_date
        - name: context_traits_notification_permission_status
        - name: context_traits_original_purchase_date
        - name: context_traits_plan
        - name: context_traits_promo
        - name: context_traits_promo_date
        - name: context_traits_received_promo
        - name: context_traits_treatment_country
        - name: context_traits_user_id
        - name: event
        - name: event_text
        - name: id
        - name: loaded_at
        - name: original_timestamp
        - name: reading_session
        - name: reading_time
        - name: received_at
        - name: referrer
        - name: sent_at
        - name: slug
        - name: timestamp
      - name: screens
        columns:
        - name: anonymous_id
        - name: category
        - name: context_app_build
        - name: context_app_name
        - name: context_app_namespace
        - name: context_app_version
        - name: context_device_id
        - name: context_device_manufacturer
        - name: context_device_model
        - name: context_device_name
        - name: context_device_token
        - name: context_device_type
        - name: context_ip
        - name: context_library_name
        - name: context_library_version
        - name: context_locale
        - name: context_network_carrier
        - name: context_network_cellular
        - name: context_network_wifi
        - name: context_os_name
        - name: context_os_version
        - name: context_screen_height
        - name: context_screen_width
        - name: context_timezone
        - name: context_traits_anonymous_id
        - name: context_traits_app_user
        - name: context_traits_email
        - name: context_traits_internal
        - name: context_traits_latest_purchase_date
        - name: context_traits_notification_permission_status
        - name: context_traits_original_purchase_date
        - name: context_traits_plan
        - name: context_traits_promo
        - name: context_traits_promo_date
        - name: context_traits_received_promo
        - name: context_traits_treatment_country
        - name: context_traits_trial
        - name: context_traits_trial_end
        - name: context_traits_trial_start
        - name: context_traits_user_id
        - name: id
        - name: loaded_at
        - name: name
        - name: original_timestamp
        - name: part
        - name: previous_treatment
        - name: received_at
        - name: sent_at
        - name: timestamp
        - name: user_id
        - name: uuid_ts
        - name: guide_title
        - name: article_id
        - name: referrer
        - name: slug
